Use number input widget in settings values
inputlabs/ctrl pull request #36
Opened 2023-12-18 18:03 UTC by marcos-diaz

![Screenshot 2023-12-18 at 18 34 43](https://github.com/inputlabs/ctrl/assets/7466304/a7d21828-904a-4ee0-8aa6-89ccdddfacd5)

2023-12-18 18:09 UTC, marcos-diaz commented on src/components/tune/tune.ts
> +
This block is moved from above with minimal changes

2023-12-18 18:10 UTC, marcos-diaz commented on src/components/profile/action_selector.sass
> -:host
Unrelated, but the compiler was throwing warnings

2023-12-19 12:28 UTC, przymi requested changes

2023-12-19 12:28 UTC, przymi commented on src/components/number_input/number_input.ts
> +  increase(dir: number) {
WTF! Too fancy! Separate inc and dec function. Please!

2023-12-19 12:36 UTC, merged